searchBox=[name='q']
username=#login1
password=#password

#Bank Manager Login
bmlBtn_CSS=body > div.ng-scope > div > div.ng-scope > div > div.borderM.box.padT20 > div:nth-child(5) > button

#Add Customer Test
addCustBtn_CSS=body > div.ng-scope > div > div.ng-scope > div > div.center > button:nth-child(1)
firstName_CSS=body > div.ng-scope > div > div.ng-scope > div > div.ng-scope > div > div > form > div:nth-child(1) > input
lastName_XPATH=body > div.ng-scope > div > div.ng-scope > div > div.ng-scope > div > div > form > div:nth-child(2) > input
postCode_CSS=body > div.ng-scope > div > div.ng-scope > div > div.ng-scope > div > div > form > div:nth-child(3) > input
addBtn_CSS=body > div.ng-scope > div > div.ng-scope > div > div.ng-scope > div > div > form > button

#Open Account
openAccount_CSS=body > div.ng-scope > div > div.ng-scope > div > div.center > button.btn.btn-lg.tab.btn-primary
customer_ID=#userSelect
currency_ID=#currency
process_CSS=button[type='submit']

#Customers

custButton_CSS=body > div.ng-scope > div > div.ng-scope > div > div.center > button:nth-child(3)
custSearch_CSS=body > div.ng-scope > div > div.ng-scope > div > div.ng-scope > div > form > div > div > input
